### ISSUE TITLE
SCALE Reg Should E-mail a Confirmation / Receipt

### ISSUE THREAD

**Issue by GoogleCodeExporter** [socallinuxexpo/scalereg#26]
```
SCALE Reg should e-mail attendees once their pass becomes valid with a 
confirmation of their pass type, and other registration details.  

We currently rely on Payflow to send payment receipts and confirmation e-mails 
to attendees.  This means that registrants who use a coupon code or pay by 
cash/check do not receive a confirmation e-mail or receipt.  Additionally it 
means that only the person who paid receives a confirmation, so if a single 
person purchases 5 tickets the actual registrants receive no notice.  This 
results in many e-mail inquiries from attendees asking us to check on a 
registrants status.


```

Original issue reported on code.google.com by `i...@fonz.net` on 26 Jan 2012 at 4:21

**Comment by irabinovitch** [comment]
This continues to be a pretty frequent request from attendees, especially when someone else pays for their pass.  We get a lot of "did i actually register? I didn't get an email confirmation" notes on events as we lead up to SCALE/TXLF/DevOpsDays/etc.

**Comment by irabinovitch** [comment]
@leizleiz I think you fixed this for SCALE 14x? Thanks!

**Comment by leizleiz** [comment]
Yes, we fixed it last year to support the Express Check-In Code feature.

**Comment by irabinovitch** [comment]
@leizleiz cool. Did we push that code up to here on github?

**Comment by leizleiz** [comment]
Not yet.
