### ISSUE TITLE
Review TLD Validation

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scalereg#34]
A user reports that his .technology domain is failing to validate during registration.  We  should review which TLDs we allow and what validation logic looks like at the moment.

https://twitter.com/treyhunner/status/689308020409421824

**Comment by treyhunner** [comment]
:+1: thanks for opening this

**Comment by irabinovitch** [comment]
@treyhunner sounds like this might be coming from core django.

**Comment by leizleiz** [comment]
We upgraded Django and this issue no longer occurs.
